### ISSUE TITLE
Repo out of sync with web store

### ISSUE THREAD

**Issue by archiif** [mrcoles/full-page-screen-capture-chrome-extension#101]
The web store's changelog lists various changes made in the past months that are not committed to this repo.

**Comment by random-un** [comment]
The bottom of [this](https://github.com/mrcoles/full-page-screen-capture-chrome-extension) page reads:

> NOTE: the webstore version is now running on a private branch of this repo and will have more updates.

Not sure when this happened, but it seems the developer sold to a private party which took over the Chrome web store page and is now making updates outside of github. This may introduce the risk of spyware? Will look into installing the open-source github version using the instructions [here](https://github.com/mrcoles/full-page-screen-capture-chrome-extension#to-install).

**Comment by mrcoles** [comment]
Hey @random-un nope, it’s still me. See this note in the FAQs for the site: https://gofullpage.com/faq#who-made-this-extension

I had to change the name from “Full Page Screen Capture” a year ago because someone else got the domain name and had a huge product hunt launch with the same name, which turns out to be non-trademarkable because it’s too descriptive. That’s why it’s now GoFullPage, see more here: https://blog.gofullpage.com/2020/07/20/introducing-gofullpage-2/

@archiif I created a private branch to focus on premium features, so I could bring in revenue to continue maintaining the extension. Taking full page screenshots is surprisingly non-trivial and there are a ton of challenges and moving parts to keep up with. Instead of having users be the product, I intentionally built out product features so people who like the extension and find it useful can contribute towards it.

Additionally, the Chrome web store has been doing much more aggressive reviewing and handling of extensions lately, which is overall a good move for extensions, since they do have elevated privileges and require a high level of trust. Since switching to use the activeTab perm in 2013, this extension has been focused on using the least permissions necessary for users and always only runs when activated.
