### ISSUE TITLE
strange beahaviour in some page

### ISSUE THREAD

**Issue by nunziofiore** [mrcoles/full-page-screen-capture-chrome-extension#19]
why (also v 0.0.9) in your opinion create repeated screen for that link?

(i attach the result) 
(as you can see, it repeat the on top screen during all the height of the page)

![screencapture-blog-screenweek-it-2013-12-vin-diesel-e-il-suo-tributo-a-paul-walker-fratello-sullo-schermo-e-nella-vita-311107-php](https://f.cloud.github.com/assets/46832/1664486/220aab78-5c28-11e3-9a84-3dc5525c7f45.png)

**Comment by JannesMeyer** [comment]
I just tried screenshotting this URL http://blog.screenweek.it/2013/12/vin-diesel-e-il-suo-tributo-a-paul-walker-fratello-sullo-schermo-e-nella-vita-311107.php

and it worked fine for me. The only issue was that the site's background got repeated and that's probably because the page is using `background-attachment: fixed;` and `position: fixed;` on some elements.

I guess you could override those rules specifically for that page before taking a screenshot by doing something like this in the console:

```
var node = document.createElement('style');
node.innerHTML = '* { background-attachment: static !important; } .takeover { position: absolute !important; } body { background: black }';
document.head.appendChild(node);
```

**Comment by mrcoles** [comment]
It has a baked-in check for fixed position headers now.

The `background-image: static` is an interesting idea. Will think about it, thanks!
