### ISSUE TITLE
Include web browser

### ISSUE THREAD

**Issue by olind** [mrcoles/full-page-screen-capture-chrome-extension#35]
Hi,
and thanks for a great chrome extension!

I have one feature request. It would be really great if it was possible to include the web browser outside the image. I use it primarily to show users how their web page looks and that would make it so simple to show :)

**Comment by mrcoles** [comment]
Unfortunately, the chrome extension API doesn't allow capturing that. Some ideas though:

1.  Check out the “other options” section of this blog post http://mrcoles.com/full-page-screen-capture-chrome-extension/

2.  You could create a template of sorts of the wrapping browser and copy the screen shot into it—that would be really troublesome though, because you'd need to make sure your browser window width matches
