### ISSUE TITLE
can not auto scroll in chrome built-in pdf viewer

### ISSUE THREAD

**Issue by QianJin2013** [mrcoles/full-page-screen-capture-chrome-extension#37]
thank you for your great works. 
I'v met a problem: when i open pdf file in chrome, it's multiple pages, but this capture tool just get one page instead of multiple pages with auto scroll.

I'v noticed that, the page's html has just one "embed" element and it occupies whole body, so document.body.clientHeight....etc is always 1 page height, but the embed element can scroll internally.

hope this can help you fix it if you have time.

**Comment by mrcoles** [comment]
Hrm… I didn’t consider PDF files, since they’re essentially printable/emailable files already (while a web page is not a standalone file). Sounds like you’re saying chrome creates a special element for this… is it scrollable via JavaScript? I’d be open to a pull request that checks for this special case and handles the scrolling inside the embed instead of the page (or in conjunction with the page? e.g., if a whole page doesn’t fit in the screen, do both the embed and the screen have to scroll?)

**Comment by QianJin2013** [comment]
Thanks for your quick response.

>>I didn’t consider PDF files, since they’re essentially
printable/emailable files already

Some pdf file are not permitted to print. This became a trick.

Not only the embed, some html use single div to do internal scrolling. So i
suguest that do not depennds on tag name.

>>is it scrollable via JavaScript?
I am not sure, it should be scrollable via java script because the embed is
expanded to another html like ihtml.

>> do both the embed and the screen have to scroll?

No, only the embed scroll.

Regards.

2015年9月10日木曜日、Peter Coles<notifications@github.com>さんは書きました:

**Comment by mrcoles** [comment]
Unfortunately it’s all hidden inside a mysterious `embed` element that doesn’t expose any methods to manipulate it, so I don’t think I can scroll it via the extension :(

**Comment by QianJin2013** [comment]
thanks.

2016年5月9日月曜日、Peter Coles<notifications@github.com>さんは書きました:
