### ISSUE TITLE
add ability to launch with a keypress

### ISSUE THREAD

**Issue by sinsunsan** [mrcoles/full-page-screen-capture-chrome-extension#41]
Thanks for this nice extension. 

I think it is a very quick alternatives to other more complicated  extension. 
Though it lack the ability to launch with a keyboard combination, which is useful, when for example you want to act on screen and copy what it show.

**Comment by mrcoles** [comment]
Hey @sinsunsan is this something a lot of other extensions support out of the box?

Chrome has support for this with *any* extension—try the following:

Go to “Window -> Extensions”, scroll down to “Keyboard Shortcuts” on the bottom right, find “Full Page Screen Capture”, and enter a shortcut, like “cmd + p” or “ctrl + p”.

**Comment by sinsunsan** [comment]
There is other extensions doing that of course.
But I like yours because it is very simple.
If it has a keyboard trigger, it could be useful at least for me.

In order not to switch to another extension just for that simple task.

**Comment by mrcoles** [comment]
Thank you @sinsunsan :smile: but did you see my comment above that you can indeed set a keyboard shortcut for it yourself? Also explained here: http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121

I guess I’ll leave this issue open, since the DIY alternative to the keyboard shortcut doesn’t suffice for many people and it looks relatively simple to add: https://developer.chrome.com/extensions/commands

**Comment by BSierakowski** [comment]
Thanks for the awesome extension, thought I'd express my excitement with a PR :). Check it out here: https://github.com/mrcoles/full-page-screen-capture-chrome-extension/pull/42 .

**Comment by mrcoles** [comment]
support will be pushed live in the next release—likely tagged as 1.0.0. 👍 for enthusiasm @BSierakowski and “fun” 😉
