### ISSUE TITLE
no longer scrolls full page

### ISSUE THREAD

**Issue by everything-it** [mrcoles/full-page-screen-capture-chrome-extension#72]
It used to work so nicely, and I'm not sure when it stopped, but it doesn't seem to scroll the pages any more.

**Comment by mrcoles** [comment]
Can you please share the URL you are trying this on? Additionally your computer type, operating system, and Chrome version?

**Comment by johnkeese** [comment]
I just experienced the same bug. Here's some info:

URL, https://www.pizzahut.com/index.php#/home
Computer, MacBook Pro OS version 10.13.1
Chrome: Version 63.0.3239.84 (Official Build) (64-bit)
Latest version of plugin installed

**Comment by mrcoles** [comment]
@johnkeese these issues are usually specific to each page, where some use non-standard scrolling in their CSS, so it’s best to report issues separately. However, since you provided some hard cold info here in the absence of any (thank you!), I’m cool with you hijacking this particular issue 😎 

I see what’s going on. `.ph-content-view` is managing its own scrollbar instead of just using the natural page scrollbar. I think I have solution I can get out in the next couple of weeks (I’ll leave this issue open). In the meantime, if you’re comfortable with the dev console, you can run the following javascript code to make it work:

```javascript
$('html,body').css({
    overflow: 'auto',
    position: 'relative',
    height: 'auto',
    minHeight: '100%'
});

$('div.custom-content-wrapper.snap-content').css({
    position: 'relative',
    width: '100%',
    minHeight: '100%',
    height: 'auto',
});

$('div.ph-content-view.content').css({
    position: 'relative',
    bottom: 'auto'
});
```

Also, I’m digging your dedication to pizza 🍕🍕🍕 in both your profile picture and example page!

@everything-it if you have more info, please open up another issue, sorry! 😨

**Comment by johnkeese** [comment]
@mrcoles yes, indeed I'm quite a pizza lover.

Hijacking the scrollbar causing the problem makes sense. Thanks for the interim solution and thanks for all the work you do on this plugin!

**Comment by mrcoles** [comment]
I’m closing this ticket. I’m well aware of this issue and have filed the info into my own tracking of scroll issues. I’ll past back when it’s sorted out. Thanks! 🍕 😋
