### ISSUE TITLE
Privacy Issue

### ISSUE THREAD

**Issue by prashantpsr24** [mrcoles/full-page-screen-capture-chrome-extension#92]
There is no way to know if this is storing the screenshots on the server.

**Comment by mrcoles** [comment]
This is a good question.

You can look at the source code here and see it doesn’t send the images anywhere.

The version in the Chrome Web store is from a private branch, because of some decisions I’ve made in the development process. It doesn’t do anything different with where it stores files other than using some newer APIs, e.g., using IndexedDB, which is a local, in-browser database. So the files only live on the device you used to capture it and only within the extension on that device, so they are not accessible to any other applications on your computer unless you download them. I wrote a little more about it here: https://gofullpage.com/faq#misc

Let me know if this helps!
