### ISSUE TITLE
Need it as a npm package

### ISSUE THREAD

**Issue by Kalaiarasan469** [mrcoles/full-page-screen-capture-chrome-extension#95]
I am trying to write a script(JS) in which I will have a website url and the script will capture the page and download it the same way the extension does in the browser.

P.S. - I am using node js.

**Comment by protecthem1** [comment]
It's been a while oles thanks

**Comment by mrcoles** [comment]
Hey @Kalaiarasan469 this is a Chrome extension. There are a couple things that I’m not fully understanding from your request to make it an npm package:

1. If it were an NPM package, then it should be a library that extracts part of this, not the whole extension
2. Because it is a Chrome extension it is using privileged APIs that the Chrome browser exposes to the extension, e.g., `chrome.tabs.executeScript`, `chrome.tabs.sendMessage`, `chrome.tabs.captureVisibleTab`, so (a) it needs to run in a browser, not node and (b) it needs to run with chrome extension privileges in order to have access to those APIs

**Comment by garyking** [comment]
Use Puppeteer for this purpose, to take screenshots with Node. Google search for "capture screenshots with puppeteer".

**Comment by Kalaiarasan469** [comment]
@mrcoles What you said was correct. As @garyking said I used puppeteer to do it. Thanks guys

**Comment by mrcoles** [comment]
Cool thanks! Yeah, the real magic of the Chrome extension is that it lets you take a screenshot of what you’re currently viewing while browsing the web, so you can capture some unique state that won’t be recreated by sharing the link with someone else. Thanks for providing a suggestion @garyking !
